/*
 * Copyright 2025-2026 The Problem4J Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.problem4j.spring.webflux;

import static io.github.problem4j.spring.web.AttributeSupport.PROBLEM_CONTEXT_ATTRIBUTE;
import static org.springframework.web.reactive.function.server.RequestPredicates.all;
import static org.springframework.web.reactive.function.server.RouterFunctions.route;

import io.github.problem4j.core.Problem;
import io.github.problem4j.core.ProblemContext;
import io.github.problem4j.spring.web.ProblemPostProcessor;
import java.util.Optional;
import org.springframework.boot.autoconfigure.web.ErrorProperties;
import org.springframework.boot.autoconfigure.web.WebProperties;
import org.springframework.boot.webflux.autoconfigure.error.DefaultErrorWebExceptionHandler;
import org.springframework.boot.webflux.error.ErrorAttributes;
import org.springframework.context.ApplicationContext;
import org.springframework.http.MediaType;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

/**
 * A WebFlux {@link org.springframework.boot.webflux.error.ErrorWebExceptionHandler} that renders
 * HTTP problems (RFC 7807) instead of the default JSON error response.
 *
 * <p>It replaces the response body with a {@link Problem} object while preserving the original HTTP
 * status and content type {@code application/problem+json}.
 *
 * @since 1.2.0
 */
public class ProblemErrorWebExceptionHandler extends DefaultErrorWebExceptionHandler {

  private final ProblemPostProcessor problemPostProcessor;

  /**
   * Constructs a new {@link ProblemErrorWebExceptionHandler}.
   *
   * @param problemPostProcessor the post-processor for problems
   * @param errorAttributes the error attributes used to obtain error details
   * @param resources configuration for static resources
   * @param errorProperties configuration for error handling
   * @param applicationContext the current application context
   * @since 1.2.0
   */
  public ProblemErrorWebExceptionHandler(
      ProblemPostProcessor problemPostProcessor,
      ErrorAttributes errorAttributes,
      WebProperties.Resources resources,
      ErrorProperties errorProperties,
      ApplicationContext applicationContext) {
    super(errorAttributes, resources, errorProperties, applicationContext);
    this.problemPostProcessor = problemPostProcessor;
  }

  /**
   * Returns a routing function that handles all requests and delegates to {@link
   * #renderErrorResponse(ServerRequest)}.
   *
   * @param errorAttributes the error attributes used to resolve errors
   * @return a routing function for handling errors
   * @see #renderErrorResponse(ServerRequest)
   * @since 1.2.0
   */
  @Override
  protected RouterFunction<ServerResponse> getRoutingFunction(ErrorAttributes errorAttributes) {
    return route(all(), this::renderErrorResponse);
  }

  /**
   * Renders an error response as a {@link Problem} in {@code application/problem+json} format.
   *
   * @param request the current server request
   * @return a {@link Mono} emitting the problem response
   * @since 1.2.0
   */
  @Override
  protected Mono<ServerResponse> renderErrorResponse(ServerRequest request) {
    return super.renderErrorResponse(request).flatMap(res -> override(request, res));
  }

  /**
   * Overrides the default error response with a {@link Problem} body.
   *
   * @param request the current server request
   * @param response the response generated by the default handler
   * @return a {@link Mono} emitting the updated response
   * @since 1.2.0
   */
  private Mono<ServerResponse> override(ServerRequest request, ServerResponse response) {
    Problem problem = Problem.of(response.statusCode().value());

    Optional<ProblemContext> optionalContext =
        request.attribute(PROBLEM_CONTEXT_ATTRIBUTE).map(context -> (ProblemContext) context);
    if (optionalContext.isPresent()) {
      ProblemContext context = optionalContext.get();
      problem = problemPostProcessor.process(context, problem);
    }

    return ServerResponse.status(problem.getStatus())
        .contentType(MediaType.APPLICATION_PROBLEM_JSON)
        .body(BodyInserters.fromValue(problem));
  }
}
