/*
 * Copyright (c) 2025-2026 The Problem4J Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.github.problem4j.spring.webflux;

import static io.github.problem4j.spring.web.AttributeSupport.PROBLEM_CONTEXT_ATTRIBUTE;
import static org.springframework.web.reactive.function.server.RequestPredicates.all;
import static org.springframework.web.reactive.function.server.RouterFunctions.route;

import io.github.problem4j.core.Problem;
import io.github.problem4j.core.ProblemContext;
import io.github.problem4j.spring.web.ProblemPostProcessor;
import java.util.Optional;
import org.springframework.boot.autoconfigure.web.ErrorProperties;
import org.springframework.boot.autoconfigure.web.WebProperties;
import org.springframework.boot.webflux.autoconfigure.error.DefaultErrorWebExceptionHandler;
import org.springframework.boot.webflux.error.ErrorAttributes;
import org.springframework.context.ApplicationContext;
import org.springframework.http.MediaType;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

/**
 * A WebFlux {@link org.springframework.boot.webflux.error.ErrorWebExceptionHandler} that renders
 * HTTP problems (RFC 7807) instead of the default JSON error response.
 *
 * <p>It replaces the response body with a {@link Problem} object while preserving the original HTTP
 * status and content type {@code application/problem+json}.
 */
public class ProblemErrorWebExceptionHandler extends DefaultErrorWebExceptionHandler {

  private final ProblemPostProcessor problemPostProcessor;

  /**
   * Constructs a new {@link ProblemErrorWebExceptionHandler}.
   *
   * @param problemPostProcessor the post-processor for problems
   * @param errorAttributes the error attributes used to obtain error details
   * @param resources configuration for static resources
   * @param errorProperties configuration for error handling
   * @param applicationContext the current application context
   */
  public ProblemErrorWebExceptionHandler(
      ProblemPostProcessor problemPostProcessor,
      ErrorAttributes errorAttributes,
      WebProperties.Resources resources,
      ErrorProperties errorProperties,
      ApplicationContext applicationContext) {
    super(errorAttributes, resources, errorProperties, applicationContext);
    this.problemPostProcessor = problemPostProcessor;
  }

  /**
   * Returns a routing function that handles all requests and delegates to {@link
   * #renderErrorResponse(ServerRequest)}.
   *
   * @param errorAttributes the error attributes used to resolve errors
   * @return a routing function for handling errors
   * @see #renderErrorResponse(ServerRequest)
   */
  @Override
  protected RouterFunction<ServerResponse> getRoutingFunction(ErrorAttributes errorAttributes) {
    return route(all(), this::renderErrorResponse);
  }

  /**
   * Renders an error response as a {@link Problem} in {@code application/problem+json} format.
   *
   * @param request the current server request
   * @return a {@link Mono} emitting the problem response
   */
  @Override
  protected Mono<ServerResponse> renderErrorResponse(ServerRequest request) {
    return super.renderErrorResponse(request).flatMap(res -> override(request, res));
  }

  /**
   * Overrides the default error response with a {@link Problem} body.
   *
   * @param request the current server request
   * @param response the response generated by the default handler
   * @return a {@link Mono} emitting the updated response
   */
  private Mono<ServerResponse> override(ServerRequest request, ServerResponse response) {
    Problem problem = Problem.of(response.statusCode().value());

    Optional<ProblemContext> optionalContext =
        request.attribute(PROBLEM_CONTEXT_ATTRIBUTE).map(context -> (ProblemContext) context);
    if (optionalContext.isPresent()) {
      ProblemContext context = optionalContext.get();
      problem = problemPostProcessor.process(context, problem);
    }

    return ServerResponse.status(problem.getStatus())
        .contentType(MediaType.APPLICATION_PROBLEM_JSON)
        .body(BodyInserters.fromValue(problem));
  }
}
