# Gradle settings
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.workers.max=4
#
# Kotlin settings
kotlin.stdlib.default.dependency=false
#
# Project settings
group=io.github.problem4j
version=2.2.4
#
# Internal buildscript settings
internal.pom.url=https://github.com/problem4j/problem4j-spring
internal.pom.inception-year=2025
internal.pom.licenses.0.name=MIT License
internal.pom.licenses.0.url=https://opensource.org/license/MIT
internal.pom.developers.0.id=malczuuu
internal.pom.developers.0.name=Damian Malczewski
internal.pom.developers.0.url=https://github.com/malczuuu
internal.pom.issue-management.system=GitHub Issues
internal.pom.issue-management.url=https://github.com/problem4j/problem4j-spring/issues
internal.pom.scm.connection=scm:git:https://github.com/problem4j/problem4j-spring.git
internal.pom.scm.developer-connection=scm:git:git@github.com:problem4j/problem4j-spring.git
internal.pom.scm.url=https://github.com/problem4j/problem4j-spring
