# Gradle settings
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.workers.max=4
#
# Kotlin settings
kotlin.stdlib.default.dependency=false
#
# Project settings
group=io.github.problem4j
version=3.0.1-SNAPSHOT
#
# Internal buildscript settings
internal.pom.url=https://problem4j.github.io
internal.pom.inception-year=2025
internal.pom.licenses.0.name=Apache License, Version 2.0
internal.pom.licenses.0.url=https://www.apache.org/licenses/LICENSE-2.0
internal.pom.developers.0.id=damianmalczewski
internal.pom.developers.0.name=Damian Malczewski
internal.pom.developers.0.url=https://github.com/damianmalczewski
internal.pom.issue-management.system=GitHub Issues
internal.pom.issue-management.url=https://github.com/problem4j/problem4j-spring/issues
internal.pom.scm.connection=scm:git:https://github.com/problem4j/problem4j-spring.git
internal.pom.scm.developer-connection=scm:git:git@github.com:problem4j/problem4j-spring.git
internal.pom.scm.url=https://github.com/problem4j/problem4j-spring
