[versions]
errorprone = "2.50.0"
errorprone-plugin = "5.1.0"
idea-ext = "1.4.1"
jspecify = "1.0.1"
kotlin = "2.4.10"
nmcp = "1.6.1"
nullaway = "0.13.8"
problem4j-core = "2.0.0"
problem4j-jackson2 = "2.0.0"
problem4j-jackson3 = "2.0.0"
spotless = "8.9.0"
spring-boot = "4.1.0"

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# direct versions
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
problem4j-core = { module = "io.github.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson2 = { module = "io.github.problem4j:problem4j-jackson2", version.ref = "problem4j-jackson2" }
problem4j-jackson3 = { module = "io.github.problem4j:problem4j-jackson3", version.ref = "problem4j-jackson3" }

# versions managed by spring-boot-dependencies
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-autoconfigure-processor = { module = "org.springframework.boot:spring-boot-autoconfigure-processor" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-jackson = { module = "org.springframework.boot:spring-boot-jackson" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-validation" }
spring-boot-web-server = { module = "org.springframework.boot:spring-boot-web-server" }
spring-boot-webflux = { module = "org.springframework.boot:spring-boot-webflux" }
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-webmvc" }
spring-boot-restclient = { module = "org.springframework.boot:spring-boot-restclient" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-web = { module = "org.springframework:spring-web" }
jackson2-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson3-dataformat-xml = { module = "tools.jackson.dataformat:jackson-dataformat-xml" }
jackson3-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
