[versions]
idea-ext = "1.4.1"
nmcp = "1.4.4"
problem4j-core = "1.4.3"
problem4j-jackson2 = "1.4.3"
spotless = "8.2.1"
spring-boot = "3.5.13"

[plugins]
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# direct versions
problem4j-core = { module = "io.github.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson2 = { module = "io.github.problem4j:problem4j-jackson2", version.ref = "problem4j-jackson2" }

# versions managed by spring-boot-dependencies
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-web = { module = "org.springframework:spring-web" }
spring-webflux = { module = "org.springframework:spring-webflux" }
spring-webmvc = { module = "org.springframework:spring-webmvc" }
jackson2-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
