/*
 * Copyright 2025-2026 The Problem4J Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.problem4j.spring.web;

import io.github.problem4j.core.Problem;
import io.github.problem4j.core.ProblemContext;
import org.jspecify.annotations.Nullable;

/**
 * Defines a contract for post-processing {@link Problem} instances before they are returned in an
 * HTTP response.
 *
 * <p>Implementations of this interface can modify, enrich, or normalize {@link Problem} objects
 * generated by the framework or application code. Typical use cases include:
 *
 * <ul>
 *   <li>Overriding standard fields such as {@code type} or {@code instance}
 *   <li>Injecting tracing or diagnostic information (e.g., a trace identifier)
 *   <li>Applying consistent formatting or metadata across all problems
 * </ul>
 *
 * <p>The interface is intentionally minimal to allow flexible extension and composition of
 * post-processing behavior.
 *
 * @since 1.2.0
 */
@FunctionalInterface
public interface ProblemPostProcessor {

  /**
   * Returns the identity {@link ProblemPostProcessor} that leaves all {@link Problem} instances
   * unchanged.
   *
   * @return the identity instance
   * @since 3.0.0
   */
  static ProblemPostProcessor identity() {
    return IdentityProblemPostProcessor.INSTANCE;
  }

  /**
   * Processes the given {@link Problem} before it is returned to the client.
   *
   * @param context the {@link ProblemContext} providing request-scoped data, such as tracing
   *     information
   * @param problem the {@link Problem} instance to process
   * @return a new or modified {@link Problem} to be returned to the client; may be the same
   *     instance if no changes are applied
   * @since 1.2.0
   */
  Problem process(@Nullable ProblemContext context, Problem problem);
}
